name: e2e_interop_test
description: End-to-end test for node interop and builders
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.2.0

dev_dependencies:
  build_runner: ^2.4.6
  build_node_compilers: ^0.3.0
  build_test: ^2.2.1
  js: ^0.6.7
  lints: ^3.0.0
  node_interop: ^2.1.2
  test: ^1.24.9
