name: build_node_compilers
version: 0.3.3
description: Builders wrapping DDC and dart2js compilers configured to output Node modules.
homepage: https://github.com/pulyaevskiy/node-interop

environment:
  sdk: ^3.2.0

dependencies:
  analyzer: ^6.3.0
  bazel_worker: ^1.1.0
  build: ^2.4.1
  build_config: ^1.1.1
  build_modules: ^5.0.5
  collection: ^1.18.0
  crypto: ^3.0.3
  logging: ^1.2.0
  node_preamble: ^2.0.2
  path: ^1.8.3
  pool: ^1.5.1
  scratch_space: ^1.0.2

dev_dependencies:
  build_test: ^2.2.1
  lints: ^3.0.0
  test: ^1.24.9
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b