name: node_http
description: HTTP client powered by Node.js I/O system.
version: 1.0.2
homepage: https://github.com/pulyaevskiy/node-interop

environment:
  sdk: ^3.2.0

dependencies:
  http: ^1.1.1
  meta: ^1.11.0
  node_interop: ^2.1.2
  node_io: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.6
  build_node_compilers: ^0.3.0
  build_test: ^2.2.1
  lints: ^3.0.0
  test: ^1.24.9
