name: node_interop
description: Provides Dart bindings and utility functions for core Node.js modules.
version: 2.1.2
homepage: https://github.com/pulyaevskiy/node-interop

environment:
  sdk: ^3.2.0

dependencies:
  js: ^0.6.7

dev_dependencies:
  build_runner: ^2.4.6
  build_node_compilers: ^0.3.0
  build_test: ^2.2.1
  lints: ^3.0.0
  test: ^1.24.9